<a href="https://colab.research.google.com/github/bharathiv38/EDA/blob/main/Ordinal_%26_Label_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("/content/customer.csv")

In [20]:
df.sample(5)

age  gender   review education purchased
19   97    Male     Poor        PG       Yes
18   19    Male     Good    School        No
46   64  Female     Poor        PG        No
42   30  Female     Good        PG       Yes
32   92    Male  Average        UG       Yes

In [21]:
df=df.iloc[:,2:]

In [22]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [25]:
X_train

review education
30  Average        UG
39     Poor        PG
36     Good        UG
21  Average        PG
43     Poor        PG
15     Poor        UG
5   Average    School
47     Good        PG
40     Good    School
32  Average        UG
18     Good    School
35     Poor    School
37  Average        PG
31     Poor    School
27     Poor        PG
9      Good        UG
16     Poor        UG
10     Good        UG
8   Average        UG
6      Good    School
7      Poor    School
1      Poor        UG
24  Average        PG
33     Good        PG
12     Poor    School
0   Average    School
42     Good        PG
28     Poor    School
20  Average    School
34  Average    School
13  Average    School
11     Good        UG
17     Poor        UG
19     Poor        PG
23     Good    School
14     Poor        PG
22     Poor        PG
49     Good        UG
3      Good        PG
38     Good    School

In [26]:
from sklearn.preprocessing import OrdinalEncoder
oe= OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [27]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [28]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [29]:
X_train

array([[1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [2., 0.]])

In [30]:
X_test

array([[1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [2., 1.]])

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [33]:
le.fit(y_train)

LabelEncoder()

In [34]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [35]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0])